import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import "./globals.css";
import 'aos/dist/aos.css';
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

// Configure Anton font
const anton = Anton({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton", // Adding a CSS variable for Anton
});

// Configure Inter font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // Adding a CSS variable for Inter
});

export const metadata: Metadata = {
  title: "Revento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${anton.variable}`}>
      <body className="font-inter"> {/* Default font is Inter */}
        <Header />
        {children}
        <Footer />

<script
  dangerouslySetInnerHTML={{
    __html: `
      var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
      (function() {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/68065990dafe3e190b1125c1/1ipccrno7';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
      })();
    `,
  }}
></script>


      </body>
    </html>
  );
}
